import { selectScores, nearLine, profile, personName, examShort, studentAt, gap } from '../model.js';
import { header, filters, examSelect, trackSelect, cohortSelect, select, segmented, metrics, metric, int, fmt, pct, signed, panel, table, tag, personLink, classLink, pillChecks, esc, button, note, empty } from '../ui.js';
export function actions(data,s,context){
 const classNos=[...new Set(selectScores(data,{exam:s.exam,track:s.track,cohort:s.cohort}).map(r=>r.classNo))].sort((a,b)=>a-b);
 const rows=selectScores(data,{...s,classes:s.classes.map(Number)}),list=nearLine(data,rows,s.tier,Number(s.window),s.side),plans=context.actions||[];
 const active=plans.filter(p=>p.status!=='done'),done=plans.filter(p=>p.status==='done');
 const candidateColumns=[{label:'姓名',render:c=>personLink(data,c.row)},{label:'班级',render:c=>classLink(c.row.classNo)},{label:'总分',numeric:true,render:c=>fmt(c.row.total)},{label:'距线',numeric:true,render:c=>'<span class="'+(c.gap<0?'negative':'positive')+'">'+signed(c.gap)+'</span>'},{label:'需要补上的学科',render:c=>c.weaknesses.map(w=>tag(w.subject+' '+signed(w.gap),'clay')).join(' ')||tag('学科均已达线','green')},{label:'最近的突破口',render:c=>c.nearest?c.nearest.subject+' · '+signed(c.nearest.gap):'总分余量巩固'},{label:'跟进',render:c=>plans.some(p=>p.sid===c.row.sid&&p.exam===s.exam&&p.tier===s.tier)?tag('已加入','green'):'<button class="btn small secondary" data-action="plan-add" data-sid="'+esc(c.row.sid)+'">加入行动</button>'}];
 const planCards=plans.map(p=>'<article class="plan-card '+(p.status==='done'?'done':'')+'"><div class="plan-head"><label><input type="checkbox" data-plan-toggle="'+esc(p.id)+'"'+(p.status==='done'?' checked':'')+'><strong>'+esc(personName(data,p.sid))+'</strong></label><button class="icon-btn" data-action="plan-remove" data-id="'+esc(p.id)+'" title="移除跟进">×</button></div><p>'+p.classNo+'班 · '+esc(examShort(data,p.exam))+' · '+(p.tier==='top'?'特控':'本科')+'线</p><div>'+tag(p.subject||'综合提升',p.status==='done'?'green':'clay')+tag(p.status==='done'?'已完成':'跟进中')+'</div><label class="plan-note"><span>下一步 · 教师记录</span><textarea data-plan-note="'+esc(p.id)+'" placeholder="具体到学生、题型和下一次复查时间…">'+esc(p.note||'')+'</textarea></label><div class="plan-date">建立于 '+esc(p.created)+'</div></article>').join('');
 const html=header('07 / FROM INSIGHT TO ACTION','把发现，变成跟进。','从临界名单到具体教学行动。每位学生的短板、最接近的突破口和教师记录，在这里汇合。')+
 filters(examSelect(data,'exam',s.exam)+trackSelect(s.track)+cohortSelect(s.cohort)+select('tier','目标层次',[['under','本科线'],['top','特控线']],s.tier)+select('window','距离范围',[[10,'10分以内'],[20,'20分以内'],[30,'30分以内'],[50,'50分以内']],s.window)+select('side','所在位置',[['below','线下待突破'],['above','线上待巩固'],['both','线上与线下']],s.side))+
 panel('班级范围','不选班级表示当前类别、届别的所有班。',pillChecks('classes',classNos.map(n=>[String(n),n+'班']),s.classes))+
 metrics(metric('本次临界学生',int(list.length),'依照你选择的距离与方向','clay')+metric('正在跟进',int(active.length),'本浏览器保存的行动记录','blue')+metric('已完成行动',int(done.length),'保留记录，便于下一次复盘','green')+metric('有待补学科',int(list.filter(c=>c.weaknesses.length).length),'学科有效线与总分线分别判断'))+
 panel('临界学生与突破口','“最近的突破口”是未达学科有效线中分差最小的一科；它是排序线索，具体安排由教师判断。',table(candidateColumns,list),button('导出临界与行动','export-view'))+
 panel('我的跟进清单','记录自动保存在本浏览器；完成后勾选，下一次复盘仍可回看。',plans.length?'<div class="plans-grid">'+planCards+'</div>':empty('从临界名单加入第一位学生','为他写下一个能执行、能追踪的下一步。'))+
 note('跟进记录属于你的本机工作区，可通过本页 Excel 导出，也会包含在工作区 JSON 备份中。重新导入数据不会主动删除教师记录。');
 return {html,sheets:{'临界学生':[['姓名','班级','总分','距线','短板学科','最近突破口'],...list.map(c=>[personName(data,c.row.sid),c.row.classNo,c.row.total,c.gap,c.weaknesses.map(w=>w.subject+' '+signed(w.gap)).join('；'),c.nearest?.subject||''])],'教师行动':[['姓名','班级','考试','目标层次','突破学科','状态','教师记录','建立日期'],...plans.map(p=>[personName(data,p.sid),p.classNo,p.exam,p.tier==='top'?'特控':'本科',p.subject,p.status==='done'?'已完成':'跟进中',p.note,p.created])]}};
}
