import { SUBJECTS, profile, latestExam, examShort, classDefaults, finite } from '../model.js';
import { header, metrics, metric, int, fmt, panel, table, segmented, button, note, select, classSelect, examSelect, filters, tag, esc, empty } from '../ui.js';
const input=(name,value,type='text',extra='')=>'<input name="'+esc(name)+'" type="'+type+'" value="'+esc(value??'')+'" '+extra+'>';
export function library(data,s){
 let body='';
 if(s.tab==='sources'){
  body='<div class="grid-two wide-left">'+panel('把原表带进来','支持标准复盘工作簿、小题工作簿、CSV、见微备份和原项目 JSON 数据。','<div class="import-drop" id="drop-zone"><div class="import-icon">↥</div><h3>拖入成绩文件，开始研究</h3><p>Excel / CSV / JSON · 可多选后依次导入</p>'+button('选择文件','import','primary')+'</div><div class="inline-controls">'+select('importMode','导入方式',[['merge','追加考次 / 补充小题'],['replace','建立新的工作区']],s.importMode)+'</div>'+note('匿名样本上导入真实成绩时会建立真实工作区，避免样本和真实学生混在一起；之后补充的小题和考次按姓名联结。'))+
  panel('你的数据，只在这里','成绩导入、分析和导出都在浏览器完成。','<div class="local-card">'+tag(data.anonymous?'当前：匿名成绩样本':'当前：本机真实成绩',data.anonymous?'blue':'green')+'<p>'+esc(data.sourceName)+'</p><small>导入时间 '+esc(new Date(data.importedAt).toLocaleString('zh-CN'))+'</small></div><div class="export-buttons">'+button('下载完整工作区备份','backup')+button('下载空白录入模板','template')+button('回到匿名样本','sample','ghost')+button('清除本机数据与记录','clear-local','danger')+'</div>')+'</div>'+
  panel('四张表，在新的工作方式里','由基础成绩、有效线和各科小题建立分析，不依赖 Excel 当前筛选后留下的展示结果。','<div class="source-mapping">'+[['班级有效人','有效达线','任务、增量、英语/日语、学科有效与双上线、线下10/20分。'],['个人学科小题得分','逐题研究 · 个人轨迹','九科逐题得分、满分、知识点、得分率与历次学科表现。'],['班级多次考试对比','纵向对照','自选考次、共同参考口径、均分/分位/达线变化与学生矩阵。'],['班级成绩分析单次','一卷透视','原分、赋分、排名、总分与六科距线、化学+生物分差。']].map(([a,b,c],i)=>'<article><span>0'+(i+1)+'</span><div><small>'+esc(a)+'</small><h3>'+esc(b)+'</h3><p>'+esc(c)+'</p></div></article>').join('')+'</div>')+
  panel('考次目录','考试名称、顺序与排名范围可在配置中编辑。',table([{label:'考次代码',key:'id'},{label:'显示名称',key:'label'},{label:'排名统计范围',render:e=>tag(e.scope==='city'?'市级考试':'校内考试')},{label:'成绩记录',numeric:true,render:e=>int(data.scores.filter(r=>r.exam===e.id).length)},{label:'小题记录',numeric:true,render:e=>int(data.answers.filter(r=>r.exam===e.id).length)}],data.exams)));
 }else if(s.tab==='configuration'){
  const p=profile(data,s.classNo),line=data.lines.find(l=>l.exam===s.lineExam&&l.track===s.lineTrack)||{subjects:{}};
  const lineSubjects=s.lineTrack==='physics'?['语文','数学','英语','日语','物理','化学','生物','地理','政治']:['语文','数学','英语','日语','历史','政治','地理','生物','化学'];
  body='<div class="grid-two">'+panel('班级资料与任务','17班、18班默认独立作为补习班；任务允许为0或留空。',classSelect(data,'classNo',s.classNo)+'<form id="profile-form"><div class="form-grid"><label class="field"><span>班主任</span>'+input('lead',p.lead)+'</label><label class="field"><span>班型名称</span>'+input('type',p.type)+'</label><label class="field"><span>类别</span><select name="track"><option value="physics"'+(p.track==='physics'?' selected':'')+'>物理类</option><option value="history"'+(p.track==='history'?' selected':'')+'>历史类</option></select></label><label class="field"><span>届别</span><select name="cohort"><option value="regular"'+(p.cohort==='regular'?' selected':'')+'>应届班</option><option value="repeat"'+(p.cohort==='repeat'?' selected':'')+'>补习班</option></select></label><label class="field"><span>选科说明</span>'+input('combination',p.combination)+'</label><label class="field"><span>外语说明</span>'+input('foreignLanguage',p.foreignLanguage)+'</label><label class="field"><span>特控人数任务</span>'+input('top',p.targets?.top,'number','min="0" step="1"')+'</label><label class="field"><span>本科人数任务</span>'+input('under',p.targets?.under,'number','min="0" step="1"')+'</label>'+SUBJECTS.map(sub=>'<label class="field"><span>'+sub+'任课教师</span>'+input('teacher-'+sub,p.teachers?.[sub])+'</label>').join('')+'</div><button class="btn primary" type="submit">保存班级配置</button></form>')+
  panel('分析口径','调整临界带、小题分组和知识点建议阈值。','<form id="rules-form"><div class="form-grid"><label class="field"><span>默认临界带（分）</span>'+input('criticalWindow',data.rules?.criticalWindow??20,'number','min="1" max="100"')+'</label><label class="field"><span>高低分组比例（%）</span>'+input('topFraction',(data.rules?.topFraction??.27)*100,'number','min="5" max="50" step="1"')+'</label><label class="field"><span>优先修复低于（%）</span>'+input('lowRate',(data.rules?.lowRate??.5)*100,'number','min="0" max="100"')+'</label><label class="field"><span>巩固迁移低于（%）</span>'+input('focusRate',(data.rules?.focusRate??.75)*100,'number','min="0" max="100"')+'</label></div><button class="btn primary" type="submit">保存分析口径</button></form>'+note('得分率与区分度只采用原表明确的题目满分。按姓名联结的历史记录，可通过工作区备份迁移到其他设备。'))+'</div>'+
  panel('总分与学科有效线','每个考次、每个类别独立设置。留空表示没有有效线，不参与达线判断。',filters(examSelect(data,'lineExam',s.lineExam,'配置考试')+select('lineTrack','配置类别',[['physics','物理类'],['history','历史类']],s.lineTrack))+'<form id="lines-form"><div class="table-wrap"><table><thead><tr><th>项目</th><th>特控有效线</th><th>本科有效线</th></tr></thead><tbody><tr><th>总分</th><td>'+input('total-top',line.top,'number','step="any"')+'</td><td>'+input('total-under',line.under,'number','step="any"')+'</td></tr>'+lineSubjects.map(sub=>'<tr><th>'+sub+'</th><td>'+input(sub+'-top',line.subjects?.[sub]?.top,'number','step="any"')+'</td><td>'+input(sub+'-under',line.subjects?.[sub]?.under,'number','step="any"')+'</td></tr>').join('')+'</tbody></table></div><button class="btn primary" type="submit">保存有效线</button></form>')+
  panel('考次名称与排序','新考次追加后可调整到合适的时间位置。','<form id="exams-form"><div class="table-wrap"><table><thead><tr><th>代码</th><th>名称</th><th>顺序</th><th>原排名范围</th></tr></thead><tbody>'+data.exams.map(e=>'<tr><td>'+esc(e.id)+'</td><td>'+input('label-'+e.id,e.label)+'</td><td>'+input('order-'+e.id,e.order,'number')+'</td><td><select name="scope-'+esc(e.id)+'"><option value="city"'+(e.scope==='city'?' selected':'')+'>市级</option><option value="school"'+(e.scope==='school'?' selected':'')+'>校内</option></select></td></tr>').join('')+'</tbody></table></div><button class="btn primary" type="submit">保存考次设置</button></form>');
 }else{
  const key=s.subject+'|'+s.bankExam,bank=data.banks[key]||[];
  body=panel('题库与知识点','补充小题满分、修改知识点，所有逐题图表与个人小题同步使用。',filters(select('subject','编辑学科',SUBJECTS,s.subject)+examSelect(data,'bankExam',s.bankExam,'编辑考试'))+(bank.length?'<form id="bank-form"><div class="table-wrap"><table><thead><tr><th>题号</th><th>原表满分文字</th><th>明确满分</th><th>知识点（逗号分隔）</th></tr></thead><tbody>'+bank.map((q,i)=>'<tr><td>'+input('label-'+i,q.label)+'</td><td>'+esc(q.sourceMax||q.maxNote||'—')+'</td><td>'+input('max-'+i,q.max,'number','min="0" step="any"')+'</td><td>'+input('knowledge-'+i,q.knowledge)+'</td></tr>').join('')+'</tbody></table></div><button class="btn primary" type="submit">保存题库</button></form>':empty('该科目、考次还没有题库','上传原始小题工作表后，题号、满分、知识点与得分会一起进入工作区。')))+
  panel('补充上传小题','小题可单独导入，按考试、班级、姓名和学科联结，不覆盖其他考试。','<p class="body-copy">支持复盘表内的各学科工作表：题号行、分值行、知识点行，以及每位学生的逐题得分。空白录入模板同时提供一张可独立上传的语文小题表。</p>'+button('选择小题工作簿','import','primary'))+
  note('导入小题原表前，先导入含真实姓名的成绩原表。地理与生物使用独立题库，日语与英语分开记录。');
 }
 const html=header('09 / YOUR DATA LIBRARY','让数据，成为可用的研究材料。','原表导入、数据备份、班级资料和有效线，都有明确的位置。')+
 metrics(metric('学生档案',int(data.students.length),data.anonymous?'匿名代称 · 分数来自原表':'姓名保存在本机','green')+metric('历次考试',int(data.exams.length),'从入口成绩到最新考试','blue')+metric('成绩记录',int(data.scores.length),'每名学生、每个考次分别保存')+metric('小题学科记录',int(data.answers.length),'每条包含该生该科全部小题','clay'))+
 '<div class="library-tabs">'+segmented('tab',[['sources','导入与备份'],['configuration','资料与口径'],['questions','小题与题库']],s.tab)+'</div>'+body;
 return {html,sheets:{}};
}
