import { selectScores, classTable, describe, subjectsFor, subjectStats, qualifies, gap, profile, finite } from '../model.js';
import { header, filters, examSelect, trackSelect, cohortSelect, select, segmented, metrics, metric, fmt, int, pct, signed, trend, panel, table, classLink, tag, meter, note, button, personLink, chartTools } from '../ui.js';
import { bars } from '../charts.js';
import { scoresSheet } from '../export.js';
const countLanguage=(data,rows,tier,lang)=>{const valid=rows.filter(r=>r.language===lang&&gap(data,r,tier)!=null);return valid.length?valid.filter(r=>qualifies(data,r,tier)).length:null;};
const band=(data,rows,tier,n)=>rows.filter(r=>{const d=gap(data,r,tier);return d!=null&&d<0&&d>=-n;}).length;
const diff=(a,b)=>finite(a)&&finite(b)?a-b:null;
const targetCell=(value,target)=>target==null?'—':target===0?'<span class="muted">未设人数任务</span>':meter(value==null?null:value/target,int(value)+' / '+int(target),value>=target?'':'clay');
export function effective(data,s){
 const all=selectScores(data,s),previous=selectScores(data,{...s,exam:s.previous}),rows=all.filter(r=>s.language==='all'||r.language===s.language),prev=previous.filter(r=>s.language==='all'||r.language===s.language);
 const classes=classTable(data,s).map(c=>({...c,rows:c.rows.filter(r=>s.language==='all'||r.language===s.language)})).map(c=>({...c,...describe(data,c.rows),prev:describe(data,prev.filter(r=>r.classNo===c.no))}));
 const d=describe(data,rows),p=describe(data,prev),subs=subjectsFor(rows);const subject=subs.includes(s.subject)?s.subject:subs[0];s.subject=subject||s.subject;
 const groupDefinitions=s.cohort==='repeat'?[[s.track==='physics'?'物理补习':'历史补习',s.track==='physics'?[17]:[18]]]:s.track==='physics'?[['1–2班教学组',[1,2]],['3–9班平行组',[3,4,5,6,7,8,9]]]:[['10班直播组',[10]],['11–14班平行组',[11,12,13,14]],['15–16班艺体组',[15,16]]];
 const groups=groupDefinitions.map(([name,nos])=>{const rs=rows.filter(r=>nos.includes(r.classNo)),ps=prev.filter(r=>nos.includes(r.classNo));return {name,nos,rows:rs,...describe(data,rs),prev:describe(data,ps)};});
 const cols=s.mode==='subjects'?
 [{label:'班级',render:r=>classLink(r.no)},{label:'任课教师',render:r=>r.profile.teachers?.[subject]||'—'},{label:'平均分',numeric:true,render:r=>fmt(subjectStats(data,r.rows,subject).avg)},{label:'均分变化',numeric:true,render:r=>trend(diff(subjectStats(data,r.rows,subject).avg,subjectStats(data,prev.filter(p=>p.classNo===r.no),subject).avg))},...['top','under'].flatMap(tier=>[{label:tier==='top'?'特控有效':'本科有效',numeric:true,render:r=>int(subjectStats(data,r.rows,subject)[tier])},{label:'双上线',numeric:true,render:r=>int(subjectStats(data,r.rows,subject)[tier+'Double'])},{label:'有效率',render:r=>meter(subjectStats(data,r.rows,subject)[tier+'Rate'])}])]:
 s.mode==='bands'?
 [{label:'班级',render:r=>classLink(r.no)},...['top','under'].flatMap(tier=>[{label:(tier==='top'?'特控':'本科')+'线下10分',numeric:true,render:r=>int(band(data,r.rows,tier,10))},{label:'线下20分（含10）',numeric:true,render:r=>int(band(data,r.rows,tier,20))},{label:'线上10分',numeric:true,render:r=>int(r.rows.filter(p=>{const g=gap(data,p,tier);return g!=null&&g>=0&&g<=10;}).length)}])]:
 [{label:'班级',render:r=>classLink(r.no)},{label:'班主任',render:r=>r.profile.lead||'—'},{label:'人数',numeric:true,render:r=>int(r.count)},{label:'均分 / 增量',numeric:true,render:r=>fmt(r.avg)+'<small class="cell-sub">'+signed(diff(r.avg,r.prev.avg))+'</small>'},...['top','under'].flatMap(tier=>[{label:tier==='top'?'特控 / 增量':'本科 / 增量',numeric:true,render:r=>int(r[tier])+'<small class="cell-sub">'+signed(diff(r[tier],r.prev[tier]),0)+'</small>'},{label:'英语 / 日语',numeric:true,render:r=>int(countLanguage(data,r.rows,tier,'英语'))+' / '+int(countLanguage(data,r.rows,tier,'日语'))},{label:'人数目标',render:r=>targetCell(r[tier],r.profile.targets?.[tier])}])];
 const critical=rows.filter(r=>{const g=gap(data,r,s.tier);return g!=null&&g<0&&g>=-20;}).sort((a,b)=>gap(data,b,s.tier)-gap(data,a,s.tier));
 const html=header('02 / EFFECTIVE ACHIEVEMENT','达线之外，还有下一步。','总分上线、学科有效、双上线和人数任务，放在同一张班级经营账里。')+
 filters(examSelect(data,'exam',s.exam)+examSelect(data,'previous',s.previous,'对照考试')+trackSelect(s.track)+cohortSelect(s.cohort)+select('language','外语口径',[['all','全部语种'],['英语','英语学生'],['日语','日语学生']],s.language))+
 metrics(metric('特控有效人数',int(d.top),'较对照 '+signed(diff(d.top,p.top),0)+' 人','green')+metric('本科有效人数',int(d.under),'较对照 '+signed(diff(d.under,p.under),0)+' 人','blue')+metric('本科线下10分',int(band(data,rows,'under',10)),'距达线最近的一组学生','clay')+metric('本科线下20分',int(band(data,rows,'under',20)),'累计口径，包含线下10分',''))+
 panel('教学组的整体变化','先合并学生记录，再计算均分与有效率；补习班作为独立教学组。',table([{label:'教学组',key:'name'},{label:'人数',numeric:true,render:g=>int(g.count)},{label:'均分',numeric:true,render:g=>fmt(g.avg)},{label:'特控 / 增量',numeric:true,render:g=>int(g.top)+' / '+signed(diff(g.top,g.prev.top),0)},{label:'本科 / 增量',numeric:true,render:g=>int(g.under)+' / '+signed(diff(g.under,g.prev.under),0)},{label:'本科率',numeric:true,render:g=>pct(g.underRate)}],groups))+
 panel('班级有效账','双上线指同一学生的学科成绩与总分均达到对应层次有效线。','<div class="inline-controls">'+segmented('mode',[['totals','总分与任务'],['subjects','学科有效'],['bands','临界带']],s.mode)+(s.mode==='subjects'?select('subject','研究学科',subs,subject):'')+'</div>'+table(cols,classes),button('导出完整有效账','export-view'))+
 '<div class="grid-two">'+panel('本科有效人数变化','同一班级，两个考次；参与人数变化请结合纵向对照观察。',bars('effective-change',classes.map(c=>({label:c.no+'班',value:diff(c.under,c.prev.under),color:diff(c.under,c.prev.under)>=0?'#226857':'#df895f'}))),chartTools('effective-change'))+
 panel('把临界变成行动','点击姓名进入轨迹，也可以转到临界行动建立跟进计划。',segmented('tier',[['under','本科临界'],['top','特控临界']],s.tier)+table([{label:'姓名',render:r=>personLink(data,r)},{label:'班级',render:r=>classLink(r.classNo)},{label:'总分',numeric:true,render:r=>fmt(r.total)},{label:'距线',numeric:true,render:r=>trend(gap(data,r,s.tier))}],critical.slice(0,10)),button('去建立跟进计划','open-actions'))+'</div>'+note('人数变化为本次减对照，不自动把均分变化解释为能力提升。人数任务可在数据书房逐班调整，体育班和美术班允许没有统一人数任务。');
 const full=[['班级','班主任','有效人数','均分','对照均分','特控人数','对照特控','特控任务','本科人数','对照本科','本科任务','特控线下10','特控线下20','本科线下10','本科线下20'],...classes.map(c=>[c.no,c.profile.lead,c.count,c.avg,c.prev.avg,c.top,c.prev.top,c.profile.targets?.top,c.under,c.prev.under,c.profile.targets?.under,band(data,c.rows,'top',10),band(data,c.rows,'top',20),band(data,c.rows,'under',10),band(data,c.rows,'under',20)])];
 const subjectSheet=[['班级','学科','教师','均分','原分均分','特控有效','特控双上线','本科有效','本科双上线','特控有效率','本科有效率'],...classes.flatMap(c=>subjectsFor(c.rows).map(sub=>{const v=subjectStats(data,c.rows,sub);return [c.no,sub,c.profile.teachers?.[sub]||'',v.avg,v.rawAvg,v.top,v.topDouble,v.under,v.underDouble,v.topRate,v.underRate];}))];
 return {html,sheets:{'班级有效人':full,'教学组汇总':[['教学组','人数','均分','特控人数','对照特控','本科人数','对照本科','本科率'],...groups.map(g=>[g.name,g.count,g.avg,g.top,g.prev.top,g.under,g.prev.under,g.underRate])],'学科有效与双上线':subjectSheet,'学生明细':scoresSheet(data,rows)}};
}
